templateDir: /local/templates/
additionalProperties:
  packageName: api
  enumClassPrefix: true
  useOneOfDiscriminatorLookup: true
files:
  README.mustache:
    templateType: SupportingFiles
    destinationFilename: README.md
