/*
authentik

Making authentication simple.

API version: 2026.8.0-rc5
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// UserSwitchActionEnum the model 'UserSwitchActionEnum'
type UserSwitchActionEnum string

// List of UserSwitchActionEnum
const (
	USERSWITCHACTIONENUM_ADD    UserSwitchActionEnum = "add"
	USERSWITCHACTIONENUM_SWITCH UserSwitchActionEnum = "switch"
)

// All allowed values of UserSwitchActionEnum enum
var AllowedUserSwitchActionEnumEnumValues = []UserSwitchActionEnum{
	"add",
	"switch",
}

func (v *UserSwitchActionEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UserSwitchActionEnum(value)
	for _, existing := range AllowedUserSwitchActionEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UserSwitchActionEnum", value)
}

// NewUserSwitchActionEnumFromValue returns a pointer to a valid UserSwitchActionEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUserSwitchActionEnumFromValue(v string) (*UserSwitchActionEnum, error) {
	ev := UserSwitchActionEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UserSwitchActionEnum: valid values are %v", v, AllowedUserSwitchActionEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UserSwitchActionEnum) IsValid() bool {
	for _, existing := range AllowedUserSwitchActionEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UserSwitchActionEnum value
func (v UserSwitchActionEnum) Ptr() *UserSwitchActionEnum {
	return &v
}

type NullableUserSwitchActionEnum struct {
	value *UserSwitchActionEnum
	isSet bool
}

func (v NullableUserSwitchActionEnum) Get() *UserSwitchActionEnum {
	return v.value
}

func (v *NullableUserSwitchActionEnum) Set(val *UserSwitchActionEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSwitchActionEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSwitchActionEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSwitchActionEnum(val *UserSwitchActionEnum) *NullableUserSwitchActionEnum {
	return &NullableUserSwitchActionEnum{value: val, isSet: true}
}

func (v NullableUserSwitchActionEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSwitchActionEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
