/*
authentik

Making authentication simple.

API version: 2025.8.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// PatchedGroupLDAPSourceConnectionRequest Group Source Connection
type PatchedGroupLDAPSourceConnectionRequest struct {
	Group      *string `json:"group,omitempty"`
	Source     *string `json:"source,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
}

// NewPatchedGroupLDAPSourceConnectionRequest instantiates a new PatchedGroupLDAPSourceConnectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedGroupLDAPSourceConnectionRequest() *PatchedGroupLDAPSourceConnectionRequest {
	this := PatchedGroupLDAPSourceConnectionRequest{}
	return &this
}

// NewPatchedGroupLDAPSourceConnectionRequestWithDefaults instantiates a new PatchedGroupLDAPSourceConnectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedGroupLDAPSourceConnectionRequestWithDefaults() *PatchedGroupLDAPSourceConnectionRequest {
	this := PatchedGroupLDAPSourceConnectionRequest{}
	return &this
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *PatchedGroupLDAPSourceConnectionRequest) GetGroup() string {
	if o == nil || o.Group == nil {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedGroupLDAPSourceConnectionRequest) GetGroupOk() (*string, bool) {
	if o == nil || o.Group == nil {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *PatchedGroupLDAPSourceConnectionRequest) HasGroup() bool {
	if o != nil && o.Group != nil {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *PatchedGroupLDAPSourceConnectionRequest) SetGroup(v string) {
	o.Group = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *PatchedGroupLDAPSourceConnectionRequest) GetSource() string {
	if o == nil || o.Source == nil {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedGroupLDAPSourceConnectionRequest) GetSourceOk() (*string, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *PatchedGroupLDAPSourceConnectionRequest) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *PatchedGroupLDAPSourceConnectionRequest) SetSource(v string) {
	o.Source = &v
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *PatchedGroupLDAPSourceConnectionRequest) GetIdentifier() string {
	if o == nil || o.Identifier == nil {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedGroupLDAPSourceConnectionRequest) GetIdentifierOk() (*string, bool) {
	if o == nil || o.Identifier == nil {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *PatchedGroupLDAPSourceConnectionRequest) HasIdentifier() bool {
	if o != nil && o.Identifier != nil {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *PatchedGroupLDAPSourceConnectionRequest) SetIdentifier(v string) {
	o.Identifier = &v
}

func (o PatchedGroupLDAPSourceConnectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Group != nil {
		toSerialize["group"] = o.Group
	}
	if o.Source != nil {
		toSerialize["source"] = o.Source
	}
	if o.Identifier != nil {
		toSerialize["identifier"] = o.Identifier
	}
	return json.Marshal(toSerialize)
}

type NullablePatchedGroupLDAPSourceConnectionRequest struct {
	value *PatchedGroupLDAPSourceConnectionRequest
	isSet bool
}

func (v NullablePatchedGroupLDAPSourceConnectionRequest) Get() *PatchedGroupLDAPSourceConnectionRequest {
	return v.value
}

func (v *NullablePatchedGroupLDAPSourceConnectionRequest) Set(val *PatchedGroupLDAPSourceConnectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedGroupLDAPSourceConnectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedGroupLDAPSourceConnectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedGroupLDAPSourceConnectionRequest(val *PatchedGroupLDAPSourceConnectionRequest) *NullablePatchedGroupLDAPSourceConnectionRequest {
	return &NullablePatchedGroupLDAPSourceConnectionRequest{value: val, isSet: true}
}

func (v NullablePatchedGroupLDAPSourceConnectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedGroupLDAPSourceConnectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
