/*
authentik

Making authentication simple.

API version: 2025.12.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GoogleEndpointDevice Serializer for Endpoint authenticator devices
type GoogleEndpointDevice struct {
	Pk *string `json:"pk,omitempty"`
	// The human-readable name of this device.
	Name string `json:"name"`
}

// NewGoogleEndpointDevice instantiates a new GoogleEndpointDevice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleEndpointDevice(name string) *GoogleEndpointDevice {
	this := GoogleEndpointDevice{}
	this.Name = name
	return &this
}

// NewGoogleEndpointDeviceWithDefaults instantiates a new GoogleEndpointDevice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleEndpointDeviceWithDefaults() *GoogleEndpointDevice {
	this := GoogleEndpointDevice{}
	return &this
}

// GetPk returns the Pk field value if set, zero value otherwise.
func (o *GoogleEndpointDevice) GetPk() string {
	if o == nil || o.Pk == nil {
		var ret string
		return ret
	}
	return *o.Pk
}

// GetPkOk returns a tuple with the Pk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleEndpointDevice) GetPkOk() (*string, bool) {
	if o == nil || o.Pk == nil {
		return nil, false
	}
	return o.Pk, true
}

// HasPk returns a boolean if a field has been set.
func (o *GoogleEndpointDevice) HasPk() bool {
	if o != nil && o.Pk != nil {
		return true
	}

	return false
}

// SetPk gets a reference to the given string and assigns it to the Pk field.
func (o *GoogleEndpointDevice) SetPk(v string) {
	o.Pk = &v
}

// GetName returns the Name field value
func (o *GoogleEndpointDevice) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GoogleEndpointDevice) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GoogleEndpointDevice) SetName(v string) {
	o.Name = v
}

func (o GoogleEndpointDevice) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pk != nil {
		toSerialize["pk"] = o.Pk
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableGoogleEndpointDevice struct {
	value *GoogleEndpointDevice
	isSet bool
}

func (v NullableGoogleEndpointDevice) Get() *GoogleEndpointDevice {
	return v.value
}

func (v *NullableGoogleEndpointDevice) Set(val *GoogleEndpointDevice) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleEndpointDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleEndpointDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleEndpointDevice(val *GoogleEndpointDevice) *NullableGoogleEndpointDevice {
	return &NullableGoogleEndpointDevice{value: val, isSet: true}
}

func (v NullableGoogleEndpointDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleEndpointDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
