/*
authentik

Making authentication simple.

API version: 2025.12.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// DeviceFactsRequestHardware struct for DeviceFactsRequestHardware
type DeviceFactsRequestHardware struct {
	Model        string  `json:"model"`
	Manufacturer string  `json:"manufacturer"`
	Serial       string  `json:"serial"`
	CpuName      *string `json:"cpu_name,omitempty"`
	CpuCount     *int32  `json:"cpu_count,omitempty"`
	MemoryBytes  *int64  `json:"memory_bytes,omitempty"`
}

// NewDeviceFactsRequestHardware instantiates a new DeviceFactsRequestHardware object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceFactsRequestHardware(model string, manufacturer string, serial string) *DeviceFactsRequestHardware {
	this := DeviceFactsRequestHardware{}
	this.Model = model
	this.Manufacturer = manufacturer
	this.Serial = serial
	return &this
}

// NewDeviceFactsRequestHardwareWithDefaults instantiates a new DeviceFactsRequestHardware object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceFactsRequestHardwareWithDefaults() *DeviceFactsRequestHardware {
	this := DeviceFactsRequestHardware{}
	return &this
}

// GetModel returns the Model field value
func (o *DeviceFactsRequestHardware) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *DeviceFactsRequestHardware) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *DeviceFactsRequestHardware) SetModel(v string) {
	o.Model = v
}

// GetManufacturer returns the Manufacturer field value
func (o *DeviceFactsRequestHardware) GetManufacturer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value
// and a boolean to check if the value has been set.
func (o *DeviceFactsRequestHardware) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Manufacturer, true
}

// SetManufacturer sets field value
func (o *DeviceFactsRequestHardware) SetManufacturer(v string) {
	o.Manufacturer = v
}

// GetSerial returns the Serial field value
func (o *DeviceFactsRequestHardware) GetSerial() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Serial
}

// GetSerialOk returns a tuple with the Serial field value
// and a boolean to check if the value has been set.
func (o *DeviceFactsRequestHardware) GetSerialOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Serial, true
}

// SetSerial sets field value
func (o *DeviceFactsRequestHardware) SetSerial(v string) {
	o.Serial = v
}

// GetCpuName returns the CpuName field value if set, zero value otherwise.
func (o *DeviceFactsRequestHardware) GetCpuName() string {
	if o == nil || o.CpuName == nil {
		var ret string
		return ret
	}
	return *o.CpuName
}

// GetCpuNameOk returns a tuple with the CpuName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceFactsRequestHardware) GetCpuNameOk() (*string, bool) {
	if o == nil || o.CpuName == nil {
		return nil, false
	}
	return o.CpuName, true
}

// HasCpuName returns a boolean if a field has been set.
func (o *DeviceFactsRequestHardware) HasCpuName() bool {
	if o != nil && o.CpuName != nil {
		return true
	}

	return false
}

// SetCpuName gets a reference to the given string and assigns it to the CpuName field.
func (o *DeviceFactsRequestHardware) SetCpuName(v string) {
	o.CpuName = &v
}

// GetCpuCount returns the CpuCount field value if set, zero value otherwise.
func (o *DeviceFactsRequestHardware) GetCpuCount() int32 {
	if o == nil || o.CpuCount == nil {
		var ret int32
		return ret
	}
	return *o.CpuCount
}

// GetCpuCountOk returns a tuple with the CpuCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceFactsRequestHardware) GetCpuCountOk() (*int32, bool) {
	if o == nil || o.CpuCount == nil {
		return nil, false
	}
	return o.CpuCount, true
}

// HasCpuCount returns a boolean if a field has been set.
func (o *DeviceFactsRequestHardware) HasCpuCount() bool {
	if o != nil && o.CpuCount != nil {
		return true
	}

	return false
}

// SetCpuCount gets a reference to the given int32 and assigns it to the CpuCount field.
func (o *DeviceFactsRequestHardware) SetCpuCount(v int32) {
	o.CpuCount = &v
}

// GetMemoryBytes returns the MemoryBytes field value if set, zero value otherwise.
func (o *DeviceFactsRequestHardware) GetMemoryBytes() int64 {
	if o == nil || o.MemoryBytes == nil {
		var ret int64
		return ret
	}
	return *o.MemoryBytes
}

// GetMemoryBytesOk returns a tuple with the MemoryBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceFactsRequestHardware) GetMemoryBytesOk() (*int64, bool) {
	if o == nil || o.MemoryBytes == nil {
		return nil, false
	}
	return o.MemoryBytes, true
}

// HasMemoryBytes returns a boolean if a field has been set.
func (o *DeviceFactsRequestHardware) HasMemoryBytes() bool {
	if o != nil && o.MemoryBytes != nil {
		return true
	}

	return false
}

// SetMemoryBytes gets a reference to the given int64 and assigns it to the MemoryBytes field.
func (o *DeviceFactsRequestHardware) SetMemoryBytes(v int64) {
	o.MemoryBytes = &v
}

func (o DeviceFactsRequestHardware) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["model"] = o.Model
	}
	if true {
		toSerialize["manufacturer"] = o.Manufacturer
	}
	if true {
		toSerialize["serial"] = o.Serial
	}
	if o.CpuName != nil {
		toSerialize["cpu_name"] = o.CpuName
	}
	if o.CpuCount != nil {
		toSerialize["cpu_count"] = o.CpuCount
	}
	if o.MemoryBytes != nil {
		toSerialize["memory_bytes"] = o.MemoryBytes
	}
	return json.Marshal(toSerialize)
}

type NullableDeviceFactsRequestHardware struct {
	value *DeviceFactsRequestHardware
	isSet bool
}

func (v NullableDeviceFactsRequestHardware) Get() *DeviceFactsRequestHardware {
	return v.value
}

func (v *NullableDeviceFactsRequestHardware) Set(val *DeviceFactsRequestHardware) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceFactsRequestHardware) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceFactsRequestHardware) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceFactsRequestHardware(val *DeviceFactsRequestHardware) *NullableDeviceFactsRequestHardware {
	return &NullableDeviceFactsRequestHardware{value: val, isSet: true}
}

func (v NullableDeviceFactsRequestHardware) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceFactsRequestHardware) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
