/*
authentik

Making authentication simple.

API version: 2025.6.1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExtraUserObjectPermissionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtraUserObjectPermissionRequest{}

// ExtraUserObjectPermissionRequest User permission with additional object-related data
type ExtraUserObjectPermissionRequest struct {
	ObjectPk string `json:"object_pk"`
}

type _ExtraUserObjectPermissionRequest ExtraUserObjectPermissionRequest

// NewExtraUserObjectPermissionRequest instantiates a new ExtraUserObjectPermissionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtraUserObjectPermissionRequest(objectPk string) *ExtraUserObjectPermissionRequest {
	this := ExtraUserObjectPermissionRequest{}
	this.ObjectPk = objectPk
	return &this
}

// NewExtraUserObjectPermissionRequestWithDefaults instantiates a new ExtraUserObjectPermissionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtraUserObjectPermissionRequestWithDefaults() *ExtraUserObjectPermissionRequest {
	this := ExtraUserObjectPermissionRequest{}
	return &this
}

// GetObjectPk returns the ObjectPk field value
func (o *ExtraUserObjectPermissionRequest) GetObjectPk() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectPk
}

// GetObjectPkOk returns a tuple with the ObjectPk field value
// and a boolean to check if the value has been set.
func (o *ExtraUserObjectPermissionRequest) GetObjectPkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectPk, true
}

// SetObjectPk sets field value
func (o *ExtraUserObjectPermissionRequest) SetObjectPk(v string) {
	o.ObjectPk = v
}

func (o ExtraUserObjectPermissionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtraUserObjectPermissionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object_pk"] = o.ObjectPk
	return toSerialize, nil
}

func (o *ExtraUserObjectPermissionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object_pk",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtraUserObjectPermissionRequest := _ExtraUserObjectPermissionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtraUserObjectPermissionRequest)

	if err != nil {
		return err
	}

	*o = ExtraUserObjectPermissionRequest(varExtraUserObjectPermissionRequest)

	return err
}

type NullableExtraUserObjectPermissionRequest struct {
	value *ExtraUserObjectPermissionRequest
	isSet bool
}

func (v NullableExtraUserObjectPermissionRequest) Get() *ExtraUserObjectPermissionRequest {
	return v.value
}

func (v *NullableExtraUserObjectPermissionRequest) Set(val *ExtraUserObjectPermissionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExtraUserObjectPermissionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExtraUserObjectPermissionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtraUserObjectPermissionRequest(val *ExtraUserObjectPermissionRequest) *NullableExtraUserObjectPermissionRequest {
	return &NullableExtraUserObjectPermissionRequest{value: val, isSet: true}
}

func (v NullableExtraUserObjectPermissionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtraUserObjectPermissionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
