/*
authentik

Making authentication simple.

API version: 2025.12.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// EndpointDeviceRequest struct for EndpointDeviceRequest
type EndpointDeviceRequest struct {
	DeviceUuid *string                `json:"device_uuid,omitempty"`
	Name       string                 `json:"name"`
	Group      NullableString         `json:"group,omitempty"`
	GroupObj   DeviceGroupRequest     `json:"group_obj"`
	Expiring   *bool                  `json:"expiring,omitempty"`
	Expires    NullableTime           `json:"expires,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
}

// NewEndpointDeviceRequest instantiates a new EndpointDeviceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointDeviceRequest(name string, groupObj DeviceGroupRequest) *EndpointDeviceRequest {
	this := EndpointDeviceRequest{}
	this.Name = name
	this.GroupObj = groupObj
	return &this
}

// NewEndpointDeviceRequestWithDefaults instantiates a new EndpointDeviceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointDeviceRequestWithDefaults() *EndpointDeviceRequest {
	this := EndpointDeviceRequest{}
	return &this
}

// GetDeviceUuid returns the DeviceUuid field value if set, zero value otherwise.
func (o *EndpointDeviceRequest) GetDeviceUuid() string {
	if o == nil || o.DeviceUuid == nil {
		var ret string
		return ret
	}
	return *o.DeviceUuid
}

// GetDeviceUuidOk returns a tuple with the DeviceUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointDeviceRequest) GetDeviceUuidOk() (*string, bool) {
	if o == nil || o.DeviceUuid == nil {
		return nil, false
	}
	return o.DeviceUuid, true
}

// HasDeviceUuid returns a boolean if a field has been set.
func (o *EndpointDeviceRequest) HasDeviceUuid() bool {
	if o != nil && o.DeviceUuid != nil {
		return true
	}

	return false
}

// SetDeviceUuid gets a reference to the given string and assigns it to the DeviceUuid field.
func (o *EndpointDeviceRequest) SetDeviceUuid(v string) {
	o.DeviceUuid = &v
}

// GetName returns the Name field value
func (o *EndpointDeviceRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EndpointDeviceRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EndpointDeviceRequest) SetName(v string) {
	o.Name = v
}

// GetGroup returns the Group field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointDeviceRequest) GetGroup() string {
	if o == nil || o.Group.Get() == nil {
		var ret string
		return ret
	}
	return *o.Group.Get()
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointDeviceRequest) GetGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Group.Get(), o.Group.IsSet()
}

// HasGroup returns a boolean if a field has been set.
func (o *EndpointDeviceRequest) HasGroup() bool {
	if o != nil && o.Group.IsSet() {
		return true
	}

	return false
}

// SetGroup gets a reference to the given NullableString and assigns it to the Group field.
func (o *EndpointDeviceRequest) SetGroup(v string) {
	o.Group.Set(&v)
}

// SetGroupNil sets the value for Group to be an explicit nil
func (o *EndpointDeviceRequest) SetGroupNil() {
	o.Group.Set(nil)
}

// UnsetGroup ensures that no value is present for Group, not even an explicit nil
func (o *EndpointDeviceRequest) UnsetGroup() {
	o.Group.Unset()
}

// GetGroupObj returns the GroupObj field value
func (o *EndpointDeviceRequest) GetGroupObj() DeviceGroupRequest {
	if o == nil {
		var ret DeviceGroupRequest
		return ret
	}

	return o.GroupObj
}

// GetGroupObjOk returns a tuple with the GroupObj field value
// and a boolean to check if the value has been set.
func (o *EndpointDeviceRequest) GetGroupObjOk() (*DeviceGroupRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupObj, true
}

// SetGroupObj sets field value
func (o *EndpointDeviceRequest) SetGroupObj(v DeviceGroupRequest) {
	o.GroupObj = v
}

// GetExpiring returns the Expiring field value if set, zero value otherwise.
func (o *EndpointDeviceRequest) GetExpiring() bool {
	if o == nil || o.Expiring == nil {
		var ret bool
		return ret
	}
	return *o.Expiring
}

// GetExpiringOk returns a tuple with the Expiring field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointDeviceRequest) GetExpiringOk() (*bool, bool) {
	if o == nil || o.Expiring == nil {
		return nil, false
	}
	return o.Expiring, true
}

// HasExpiring returns a boolean if a field has been set.
func (o *EndpointDeviceRequest) HasExpiring() bool {
	if o != nil && o.Expiring != nil {
		return true
	}

	return false
}

// SetExpiring gets a reference to the given bool and assigns it to the Expiring field.
func (o *EndpointDeviceRequest) SetExpiring(v bool) {
	o.Expiring = &v
}

// GetExpires returns the Expires field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointDeviceRequest) GetExpires() time.Time {
	if o == nil || o.Expires.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.Expires.Get()
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointDeviceRequest) GetExpiresOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Expires.Get(), o.Expires.IsSet()
}

// HasExpires returns a boolean if a field has been set.
func (o *EndpointDeviceRequest) HasExpires() bool {
	if o != nil && o.Expires.IsSet() {
		return true
	}

	return false
}

// SetExpires gets a reference to the given NullableTime and assigns it to the Expires field.
func (o *EndpointDeviceRequest) SetExpires(v time.Time) {
	o.Expires.Set(&v)
}

// SetExpiresNil sets the value for Expires to be an explicit nil
func (o *EndpointDeviceRequest) SetExpiresNil() {
	o.Expires.Set(nil)
}

// UnsetExpires ensures that no value is present for Expires, not even an explicit nil
func (o *EndpointDeviceRequest) UnsetExpires() {
	o.Expires.Unset()
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *EndpointDeviceRequest) GetAttributes() map[string]interface{} {
	if o == nil || o.Attributes == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointDeviceRequest) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *EndpointDeviceRequest) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *EndpointDeviceRequest) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

func (o EndpointDeviceRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DeviceUuid != nil {
		toSerialize["device_uuid"] = o.DeviceUuid
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Group.IsSet() {
		toSerialize["group"] = o.Group.Get()
	}
	if true {
		toSerialize["group_obj"] = o.GroupObj
	}
	if o.Expiring != nil {
		toSerialize["expiring"] = o.Expiring
	}
	if o.Expires.IsSet() {
		toSerialize["expires"] = o.Expires.Get()
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableEndpointDeviceRequest struct {
	value *EndpointDeviceRequest
	isSet bool
}

func (v NullableEndpointDeviceRequest) Get() *EndpointDeviceRequest {
	return v.value
}

func (v *NullableEndpointDeviceRequest) Set(val *EndpointDeviceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointDeviceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointDeviceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointDeviceRequest(val *EndpointDeviceRequest) *NullableEndpointDeviceRequest {
	return &NullableEndpointDeviceRequest{value: val, isSet: true}
}

func (v NullableEndpointDeviceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointDeviceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
