/*
authentik

Making authentication simple.

API version: 2026.8.0-rc7
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedRequestableTargetList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedRequestableTargetList{}

// PaginatedRequestableTargetList struct for PaginatedRequestableTargetList
type PaginatedRequestableTargetList struct {
	Pagination           Pagination             `json:"pagination"`
	Results              []RequestableTarget    `json:"results"`
	Autocomplete         map[string]interface{} `json:"autocomplete"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedRequestableTargetList PaginatedRequestableTargetList

// NewPaginatedRequestableTargetList instantiates a new PaginatedRequestableTargetList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedRequestableTargetList(pagination Pagination, results []RequestableTarget, autocomplete map[string]interface{}) *PaginatedRequestableTargetList {
	this := PaginatedRequestableTargetList{}
	this.Pagination = pagination
	this.Results = results
	this.Autocomplete = autocomplete
	return &this
}

// NewPaginatedRequestableTargetListWithDefaults instantiates a new PaginatedRequestableTargetList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedRequestableTargetListWithDefaults() *PaginatedRequestableTargetList {
	this := PaginatedRequestableTargetList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *PaginatedRequestableTargetList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedRequestableTargetList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedRequestableTargetList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetResults returns the Results field value
func (o *PaginatedRequestableTargetList) GetResults() []RequestableTarget {
	if o == nil {
		var ret []RequestableTarget
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedRequestableTargetList) GetResultsOk() ([]RequestableTarget, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedRequestableTargetList) SetResults(v []RequestableTarget) {
	o.Results = v
}

// GetAutocomplete returns the Autocomplete field value
func (o *PaginatedRequestableTargetList) GetAutocomplete() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Autocomplete
}

// GetAutocompleteOk returns a tuple with the Autocomplete field value
// and a boolean to check if the value has been set.
func (o *PaginatedRequestableTargetList) GetAutocompleteOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Autocomplete, true
}

// SetAutocomplete sets field value
func (o *PaginatedRequestableTargetList) SetAutocomplete(v map[string]interface{}) {
	o.Autocomplete = v
}

func (o PaginatedRequestableTargetList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedRequestableTargetList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["results"] = o.Results
	toSerialize["autocomplete"] = o.Autocomplete

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedRequestableTargetList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pagination",
		"results",
		"autocomplete",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedRequestableTargetList := _PaginatedRequestableTargetList{}

	err = json.Unmarshal(data, &varPaginatedRequestableTargetList)

	if err != nil {
		return err
	}

	*o = PaginatedRequestableTargetList(varPaginatedRequestableTargetList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pagination")
		delete(additionalProperties, "results")
		delete(additionalProperties, "autocomplete")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedRequestableTargetList struct {
	value *PaginatedRequestableTargetList
	isSet bool
}

func (v NullablePaginatedRequestableTargetList) Get() *PaginatedRequestableTargetList {
	return v.value
}

func (v *NullablePaginatedRequestableTargetList) Set(val *PaginatedRequestableTargetList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedRequestableTargetList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedRequestableTargetList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedRequestableTargetList(val *PaginatedRequestableTargetList) *NullablePaginatedRequestableTargetList {
	return &NullablePaginatedRequestableTargetList{value: val, isSet: true}
}

func (v NullablePaginatedRequestableTargetList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedRequestableTargetList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
