/*
authentik

Making authentication simple.

API version: 2025.12.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// DeviceAccessGroupRequest struct for DeviceAccessGroupRequest
type DeviceAccessGroupRequest struct {
	Name string `json:"name"`
}

// NewDeviceAccessGroupRequest instantiates a new DeviceAccessGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceAccessGroupRequest(name string) *DeviceAccessGroupRequest {
	this := DeviceAccessGroupRequest{}
	this.Name = name
	return &this
}

// NewDeviceAccessGroupRequestWithDefaults instantiates a new DeviceAccessGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceAccessGroupRequestWithDefaults() *DeviceAccessGroupRequest {
	this := DeviceAccessGroupRequest{}
	return &this
}

// GetName returns the Name field value
func (o *DeviceAccessGroupRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeviceAccessGroupRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeviceAccessGroupRequest) SetName(v string) {
	o.Name = v
}

func (o DeviceAccessGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableDeviceAccessGroupRequest struct {
	value *DeviceAccessGroupRequest
	isSet bool
}

func (v NullableDeviceAccessGroupRequest) Get() *DeviceAccessGroupRequest {
	return v.value
}

func (v *NullableDeviceAccessGroupRequest) Set(val *DeviceAccessGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceAccessGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceAccessGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceAccessGroupRequest(val *DeviceAccessGroupRequest) *NullableDeviceAccessGroupRequest {
	return &NullableDeviceAccessGroupRequest{value: val, isSet: true}
}

func (v NullableDeviceAccessGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceAccessGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
