/*
authentik

Making authentication simple.

API version: 2026.8.0-rc4
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedOAuth2DynamicClientRegistrationList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedOAuth2DynamicClientRegistrationList{}

// PaginatedOAuth2DynamicClientRegistrationList struct for PaginatedOAuth2DynamicClientRegistrationList
type PaginatedOAuth2DynamicClientRegistrationList struct {
	Pagination           Pagination                        `json:"pagination"`
	Results              []OAuth2DynamicClientRegistration `json:"results"`
	Autocomplete         map[string]interface{}            `json:"autocomplete"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedOAuth2DynamicClientRegistrationList PaginatedOAuth2DynamicClientRegistrationList

// NewPaginatedOAuth2DynamicClientRegistrationList instantiates a new PaginatedOAuth2DynamicClientRegistrationList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedOAuth2DynamicClientRegistrationList(pagination Pagination, results []OAuth2DynamicClientRegistration, autocomplete map[string]interface{}) *PaginatedOAuth2DynamicClientRegistrationList {
	this := PaginatedOAuth2DynamicClientRegistrationList{}
	this.Pagination = pagination
	this.Results = results
	this.Autocomplete = autocomplete
	return &this
}

// NewPaginatedOAuth2DynamicClientRegistrationListWithDefaults instantiates a new PaginatedOAuth2DynamicClientRegistrationList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedOAuth2DynamicClientRegistrationListWithDefaults() *PaginatedOAuth2DynamicClientRegistrationList {
	this := PaginatedOAuth2DynamicClientRegistrationList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *PaginatedOAuth2DynamicClientRegistrationList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedOAuth2DynamicClientRegistrationList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedOAuth2DynamicClientRegistrationList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetResults returns the Results field value
func (o *PaginatedOAuth2DynamicClientRegistrationList) GetResults() []OAuth2DynamicClientRegistration {
	if o == nil {
		var ret []OAuth2DynamicClientRegistration
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedOAuth2DynamicClientRegistrationList) GetResultsOk() ([]OAuth2DynamicClientRegistration, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedOAuth2DynamicClientRegistrationList) SetResults(v []OAuth2DynamicClientRegistration) {
	o.Results = v
}

// GetAutocomplete returns the Autocomplete field value
func (o *PaginatedOAuth2DynamicClientRegistrationList) GetAutocomplete() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Autocomplete
}

// GetAutocompleteOk returns a tuple with the Autocomplete field value
// and a boolean to check if the value has been set.
func (o *PaginatedOAuth2DynamicClientRegistrationList) GetAutocompleteOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Autocomplete, true
}

// SetAutocomplete sets field value
func (o *PaginatedOAuth2DynamicClientRegistrationList) SetAutocomplete(v map[string]interface{}) {
	o.Autocomplete = v
}

func (o PaginatedOAuth2DynamicClientRegistrationList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedOAuth2DynamicClientRegistrationList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["results"] = o.Results
	toSerialize["autocomplete"] = o.Autocomplete

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedOAuth2DynamicClientRegistrationList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pagination",
		"results",
		"autocomplete",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedOAuth2DynamicClientRegistrationList := _PaginatedOAuth2DynamicClientRegistrationList{}

	err = json.Unmarshal(data, &varPaginatedOAuth2DynamicClientRegistrationList)

	if err != nil {
		return err
	}

	*o = PaginatedOAuth2DynamicClientRegistrationList(varPaginatedOAuth2DynamicClientRegistrationList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pagination")
		delete(additionalProperties, "results")
		delete(additionalProperties, "autocomplete")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedOAuth2DynamicClientRegistrationList struct {
	value *PaginatedOAuth2DynamicClientRegistrationList
	isSet bool
}

func (v NullablePaginatedOAuth2DynamicClientRegistrationList) Get() *PaginatedOAuth2DynamicClientRegistrationList {
	return v.value
}

func (v *NullablePaginatedOAuth2DynamicClientRegistrationList) Set(val *PaginatedOAuth2DynamicClientRegistrationList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedOAuth2DynamicClientRegistrationList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedOAuth2DynamicClientRegistrationList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedOAuth2DynamicClientRegistrationList(val *PaginatedOAuth2DynamicClientRegistrationList) *NullablePaginatedOAuth2DynamicClientRegistrationList {
	return &NullablePaginatedOAuth2DynamicClientRegistrationList{value: val, isSet: true}
}

func (v NullablePaginatedOAuth2DynamicClientRegistrationList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedOAuth2DynamicClientRegistrationList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
