/*
authentik

Making authentication simple.

API version: 2025.10.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// PaginatedTenantList struct for PaginatedTenantList
type PaginatedTenantList struct {
	Pagination   Pagination             `json:"pagination"`
	Results      []Tenant               `json:"results"`
	Autocomplete map[string]interface{} `json:"autocomplete"`
}

// NewPaginatedTenantList instantiates a new PaginatedTenantList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedTenantList(pagination Pagination, results []Tenant, autocomplete map[string]interface{}) *PaginatedTenantList {
	this := PaginatedTenantList{}
	this.Pagination = pagination
	this.Results = results
	this.Autocomplete = autocomplete
	return &this
}

// NewPaginatedTenantListWithDefaults instantiates a new PaginatedTenantList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedTenantListWithDefaults() *PaginatedTenantList {
	this := PaginatedTenantList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *PaginatedTenantList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedTenantList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedTenantList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetResults returns the Results field value
func (o *PaginatedTenantList) GetResults() []Tenant {
	if o == nil {
		var ret []Tenant
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedTenantList) GetResultsOk() ([]Tenant, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedTenantList) SetResults(v []Tenant) {
	o.Results = v
}

// GetAutocomplete returns the Autocomplete field value
func (o *PaginatedTenantList) GetAutocomplete() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Autocomplete
}

// GetAutocompleteOk returns a tuple with the Autocomplete field value
// and a boolean to check if the value has been set.
func (o *PaginatedTenantList) GetAutocompleteOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Autocomplete, true
}

// SetAutocomplete sets field value
func (o *PaginatedTenantList) SetAutocomplete(v map[string]interface{}) {
	o.Autocomplete = v
}

func (o PaginatedTenantList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pagination"] = o.Pagination
	}
	if true {
		toSerialize["results"] = o.Results
	}
	if true {
		toSerialize["autocomplete"] = o.Autocomplete
	}
	return json.Marshal(toSerialize)
}

type NullablePaginatedTenantList struct {
	value *PaginatedTenantList
	isSet bool
}

func (v NullablePaginatedTenantList) Get() *PaginatedTenantList {
	return v.value
}

func (v *NullablePaginatedTenantList) Set(val *PaginatedTenantList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedTenantList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedTenantList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedTenantList(val *PaginatedTenantList) *NullablePaginatedTenantList {
	return &NullablePaginatedTenantList{value: val, isSet: true}
}

func (v NullablePaginatedTenantList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedTenantList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
