/*
authentik

Making authentication simple.

API version: 2024.12.0
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// PaginatedGoogleWorkspaceProviderUserList struct for PaginatedGoogleWorkspaceProviderUserList
type PaginatedGoogleWorkspaceProviderUserList struct {
	Pagination Pagination                    `json:"pagination"`
	Results    []GoogleWorkspaceProviderUser `json:"results"`
}

// NewPaginatedGoogleWorkspaceProviderUserList instantiates a new PaginatedGoogleWorkspaceProviderUserList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedGoogleWorkspaceProviderUserList(pagination Pagination, results []GoogleWorkspaceProviderUser) *PaginatedGoogleWorkspaceProviderUserList {
	this := PaginatedGoogleWorkspaceProviderUserList{}
	this.Pagination = pagination
	this.Results = results
	return &this
}

// NewPaginatedGoogleWorkspaceProviderUserListWithDefaults instantiates a new PaginatedGoogleWorkspaceProviderUserList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedGoogleWorkspaceProviderUserListWithDefaults() *PaginatedGoogleWorkspaceProviderUserList {
	this := PaginatedGoogleWorkspaceProviderUserList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *PaginatedGoogleWorkspaceProviderUserList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedGoogleWorkspaceProviderUserList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedGoogleWorkspaceProviderUserList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetResults returns the Results field value
func (o *PaginatedGoogleWorkspaceProviderUserList) GetResults() []GoogleWorkspaceProviderUser {
	if o == nil {
		var ret []GoogleWorkspaceProviderUser
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedGoogleWorkspaceProviderUserList) GetResultsOk() ([]GoogleWorkspaceProviderUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedGoogleWorkspaceProviderUserList) SetResults(v []GoogleWorkspaceProviderUser) {
	o.Results = v
}

func (o PaginatedGoogleWorkspaceProviderUserList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pagination"] = o.Pagination
	}
	if true {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullablePaginatedGoogleWorkspaceProviderUserList struct {
	value *PaginatedGoogleWorkspaceProviderUserList
	isSet bool
}

func (v NullablePaginatedGoogleWorkspaceProviderUserList) Get() *PaginatedGoogleWorkspaceProviderUserList {
	return v.value
}

func (v *NullablePaginatedGoogleWorkspaceProviderUserList) Set(val *PaginatedGoogleWorkspaceProviderUserList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedGoogleWorkspaceProviderUserList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedGoogleWorkspaceProviderUserList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedGoogleWorkspaceProviderUserList(val *PaginatedGoogleWorkspaceProviderUserList) *NullablePaginatedGoogleWorkspaceProviderUserList {
	return &NullablePaginatedGoogleWorkspaceProviderUserList{value: val, isSet: true}
}

func (v NullablePaginatedGoogleWorkspaceProviderUserList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedGoogleWorkspaceProviderUserList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
