/*
authentik

Making authentication simple.

API version: 2026.5.3
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the UserKerberosSourceConnectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserKerberosSourceConnectionRequest{}

// UserKerberosSourceConnectionRequest User source connection
type UserKerberosSourceConnectionRequest struct {
	Source               string `json:"source"`
	Identifier           string `json:"identifier"`
	AdditionalProperties map[string]interface{}
}

type _UserKerberosSourceConnectionRequest UserKerberosSourceConnectionRequest

// NewUserKerberosSourceConnectionRequest instantiates a new UserKerberosSourceConnectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserKerberosSourceConnectionRequest(source string, identifier string) *UserKerberosSourceConnectionRequest {
	this := UserKerberosSourceConnectionRequest{}
	this.Source = source
	this.Identifier = identifier
	return &this
}

// NewUserKerberosSourceConnectionRequestWithDefaults instantiates a new UserKerberosSourceConnectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserKerberosSourceConnectionRequestWithDefaults() *UserKerberosSourceConnectionRequest {
	this := UserKerberosSourceConnectionRequest{}
	return &this
}

// GetSource returns the Source field value
func (o *UserKerberosSourceConnectionRequest) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *UserKerberosSourceConnectionRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *UserKerberosSourceConnectionRequest) SetSource(v string) {
	o.Source = v
}

// GetIdentifier returns the Identifier field value
func (o *UserKerberosSourceConnectionRequest) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *UserKerberosSourceConnectionRequest) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *UserKerberosSourceConnectionRequest) SetIdentifier(v string) {
	o.Identifier = v
}

func (o UserKerberosSourceConnectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserKerberosSourceConnectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["identifier"] = o.Identifier

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserKerberosSourceConnectionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"identifier",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserKerberosSourceConnectionRequest := _UserKerberosSourceConnectionRequest{}

	err = json.Unmarshal(data, &varUserKerberosSourceConnectionRequest)

	if err != nil {
		return err
	}

	*o = UserKerberosSourceConnectionRequest(varUserKerberosSourceConnectionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "source")
		delete(additionalProperties, "identifier")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserKerberosSourceConnectionRequest struct {
	value *UserKerberosSourceConnectionRequest
	isSet bool
}

func (v NullableUserKerberosSourceConnectionRequest) Get() *UserKerberosSourceConnectionRequest {
	return v.value
}

func (v *NullableUserKerberosSourceConnectionRequest) Set(val *UserKerberosSourceConnectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserKerberosSourceConnectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserKerberosSourceConnectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserKerberosSourceConnectionRequest(val *UserKerberosSourceConnectionRequest) *NullableUserKerberosSourceConnectionRequest {
	return &NullableUserKerberosSourceConnectionRequest{value: val, isSet: true}
}

func (v NullableUserKerberosSourceConnectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserKerberosSourceConnectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
