/*
authentik

Making authentication simple.

API version: 2025.12.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// DeviceConnectionLatestSnapshot struct for DeviceConnectionLatestSnapshot
type DeviceConnectionLatestSnapshot struct {
	Data       DeviceFacts  `json:"data"`
	Connection string       `json:"connection"`
	Created    time.Time    `json:"created"`
	Expires    NullableTime `json:"expires"`
}

// NewDeviceConnectionLatestSnapshot instantiates a new DeviceConnectionLatestSnapshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceConnectionLatestSnapshot(data DeviceFacts, connection string, created time.Time, expires NullableTime) *DeviceConnectionLatestSnapshot {
	this := DeviceConnectionLatestSnapshot{}
	this.Data = data
	this.Connection = connection
	this.Created = created
	this.Expires = expires
	return &this
}

// NewDeviceConnectionLatestSnapshotWithDefaults instantiates a new DeviceConnectionLatestSnapshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceConnectionLatestSnapshotWithDefaults() *DeviceConnectionLatestSnapshot {
	this := DeviceConnectionLatestSnapshot{}
	return &this
}

// GetData returns the Data field value
func (o *DeviceConnectionLatestSnapshot) GetData() DeviceFacts {
	if o == nil {
		var ret DeviceFacts
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeviceConnectionLatestSnapshot) GetDataOk() (*DeviceFacts, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeviceConnectionLatestSnapshot) SetData(v DeviceFacts) {
	o.Data = v
}

// GetConnection returns the Connection field value
func (o *DeviceConnectionLatestSnapshot) GetConnection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Connection
}

// GetConnectionOk returns a tuple with the Connection field value
// and a boolean to check if the value has been set.
func (o *DeviceConnectionLatestSnapshot) GetConnectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connection, true
}

// SetConnection sets field value
func (o *DeviceConnectionLatestSnapshot) SetConnection(v string) {
	o.Connection = v
}

// GetCreated returns the Created field value
func (o *DeviceConnectionLatestSnapshot) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *DeviceConnectionLatestSnapshot) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *DeviceConnectionLatestSnapshot) SetCreated(v time.Time) {
	o.Created = v
}

// GetExpires returns the Expires field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DeviceConnectionLatestSnapshot) GetExpires() time.Time {
	if o == nil || o.Expires.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.Expires.Get()
}

// GetExpiresOk returns a tuple with the Expires field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceConnectionLatestSnapshot) GetExpiresOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Expires.Get(), o.Expires.IsSet()
}

// SetExpires sets field value
func (o *DeviceConnectionLatestSnapshot) SetExpires(v time.Time) {
	o.Expires.Set(&v)
}

func (o DeviceConnectionLatestSnapshot) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["connection"] = o.Connection
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["expires"] = o.Expires.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableDeviceConnectionLatestSnapshot struct {
	value *DeviceConnectionLatestSnapshot
	isSet bool
}

func (v NullableDeviceConnectionLatestSnapshot) Get() *DeviceConnectionLatestSnapshot {
	return v.value
}

func (v *NullableDeviceConnectionLatestSnapshot) Set(val *DeviceConnectionLatestSnapshot) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceConnectionLatestSnapshot) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceConnectionLatestSnapshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceConnectionLatestSnapshot(val *DeviceConnectionLatestSnapshot) *NullableDeviceConnectionLatestSnapshot {
	return &NullableDeviceConnectionLatestSnapshot{value: val, isSet: true}
}

func (v NullableDeviceConnectionLatestSnapshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceConnectionLatestSnapshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
